config/routes.rb
Rails.application.routes.draw do
  resources :share, only: %i(index create show destroy)
  resources :restore, only: %i(index update)
  resources :recents, only: :index
  resources :favorites, only: %i(index create destroy)

  resources :about, only: :index
  resources :help, only: :index

  resources :folders, only: %i(index show create update destroy) do
    resources :items, only: %i(create destroy show)
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  root 'home#index'
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? "Itembox | #{yield(:title)}" : "Itembox"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script><
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Itembox', root_path, class: "brand"
          .container.nav-collapse
            %ul.nav.pull-right
              %li.divider-vertical
              %li= link_to t('links.profile'), edit_user_registration_path
              %li.divider-vertical
              %li= link_to t('links.logout'), destroy_user_session_path, method: :delete
          / /.nav-collapse
    .container
      .row
        .span9
          - if notice
            .alert.alert-success
              %button.close{"data-dismiss" => "alert", :type => "button"} ×
              = notice
          - if alert
            .alert.alert-error
              %button.close{"data-dismiss" => "alert", :type => "button"} ×
              = alert
          = yield
        .span3
          .sidebar-nav
            %ul.nav.nav-list
              %li
                %span#used_space= t('progress_bar.title',
                first_value: number_to_human_size(current_user.used_space),
                second_value: number_to_human_size(current_user.space))
              %li
                #space-progress.progress
                  #usedspace-bar.bar.bar-danger{:style => "width: #{current_user.try(:used_space_percent)}%;"}
                  #freespace-bar.bar.bar-success{:style => "width: #{current_user.try(:free_space_percent)}%;"}
              %li= link_to t('links.home'), root_path
              %li= link_to t('links.recents'), recents_path
              %li= link_to t('links.favorites'), favorites_path
              %li= link_to t('links.shared'), share_index_path
              %li= link_to t('links.deleted'), restore_index_path
          / /.well
        / /span
      / /row
      %footer
        %ul.breadcrumb{:align => "center"}
          %li
            © Itembox #{Time.zone.now.year}
            %span.divider /
          %li
            = link_to t('links.home'), root_path
            %span.divider /
          %li= link_to t('links.about'), about_index_path
    / /container

app/views/layouts/registration.html.haml
!!!
%html{lang: 'ru'}
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %meta{:charset => 'utf-8'}/
    %meta{:content => 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible'}/
    %meta{:content => 'width=device-width, initial-scale=1.0', :name => 'viewport'}/
    %title= content_for?(:title) ? (yield :title) + ' | Itembox' : 'Itembox'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script><
    = stylesheet_link_tag 'application', media: 'all'
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application'
  %body
    = yield