config/routes.rb
Rails.application.routes.draw do
  resources :share, only: %i(index create show destroy)
  resources :restore, only: %i(index update)
  resources :recents, only: :index
  resources :favorites, only: %i(index create destroy)

  resources :about, only: :index
  resources :help, only: :index

  resources :folders, only: %i(index show create update destroy) do
    resources :items, only: %i(create destroy show)
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  root 'home#index'
end

app/controllers/restore_controller.rb
class RestoreController < ApplicationController
  def index
    @items = current_user.items.only_deleted
  end

  def update
    restore_service = RestoreService.new(current_user, params[:id])
    restore_service.restore
    redirect_to restore_service.folder
  end
end

app/views/restore/index.html.haml
- title t('links.deleted')
%table#main-table.table.table-striped.tablesorter
  = t('table.titles.last_month')
  %tbody
    %tr
      %td= t('table.titles.name')
      %td= t('table.titles.modified')
      %td= t('table.titles.size')
      %td= t('table.titles.actions')
    - @items.each do |item|
      %tr.items
        %td
          %i.icon-file
          = link_to item.filename, folder_item_path(current_folder, item)
        %td= humanize_date_in_time_zone(item.deleted_at)
        %td= number_to_human_size(item.size)
        %td= link_to ApplicationHelper::BLANK_LINK, restore_path(item), method: :put, class: 'icon-leaf', title: 'Restore'